### ISSUE TITLE
NGINX Crash

### ISSUE THREAD

**Issue by rolandplanitz** [Creamfinance/clashing-coders-rpg#2]
Hi, I tried to start the NGINX Server with your given config but it won't accept it.

```
[roland@Turtle:~/git/clashing-coders-rpg] % sudo nginx -c ~/git/clashing-coders-rpg/clashing-coders.nginx.conf -t
nginx: [emerg] "upstream" directive is not allowed here in /Users/roland/git/clashing-coders-rpg/clashing-coders.nginx.conf:1
nginx: configuration file /Users/roland/git/clashing-coders-rpg/clashing-coders.nginx.conf test failed
```

Is there something wrong with the NGINX Config or with my NGINX?

**Comment by RianFuro** [comment]
The config is not supposed to be used standalone (as the directives used in there are only allowed within an http section within NGINX).

Instead, you are either supposed to wrap the content of that file into an http section like so:

``` nginx
http {
    #[our configuration here]
}
```

Or, what I recommend, use the NGINX default config, which should come with a section like so:

``` nginx
# Load modular configuration files from the /etc/nginx/conf.d directory.
# See http://nginx.org/en/docs/ngx_core_module.html#include
# for more information.
include /etc/nginx/conf.d/*.conf;
```

within the http section.

This allows you to use a configuration directory (defaults to `/etc/nginx/conf.d/`) where config files are loaded from. We are using a modular configuration here because we are working on a bunch of webservices at the same time; so a modular configuration approach makes it easy to set up dev environments.

**Comment by RianFuro** [comment]
I suppose I can enhance the readme a little to make that more obvious...

**Comment by rolandplanitz** [comment]
Thanks, that helped a bit. 
I have now my default NGINX config which loads everything from a specific folder.
I created a symlink to the git repository, so it should load your config.

but when I go to localhost:8080 as in the config, I get a blank white page.

In your config there is a part that I don't get. Should I edit this for my git repository?

```
...
root /data/coding-contest-platform/public;

        location / {
                root /data/coding-contest-platform/public;
                try_files $uri @node;
        }
...
```

In my Git working directory I have a public folder, but there is no index.html and /data/coding-contest-plattform doesn't really point at something on my machine.

**Comment by RianFuro** [comment]
Yeah, you have to change those 2 paths to correspond to wherever-you-cloned-the-repository-to's public folder (I believe that part is in the instruction already)
You won't need an index.html as nginx's part in this is only to serve static files like images and stylesheets, while node should serve the pages.

A bit of background:
The `try_files` part in the nginx config does exactly what it suggests - if a request comes in it uses the arguments from try_files in order; so it will first take the uri and check if it is a file path relative to what is defined in the `root ...` line. 
If that won't work, it will then pass the request to the node service, by passing it to the "node" location via `@node`, which will then redirect it to the defined upstream.
The node service then is of course our coding contest platform, which implements a very basic MVC pattern to resolve the route to a controller, which will render a view (usually via a template system) and respond with that.
I haven't gotten to document the routes it accepts into the readme (I have to do actual "work" at work after all^^), but you can easily look that up in the controllers; each controller has a `registerRouter` function which will register it's routes into the dispatcher. The token for the admin routes is simply hardcoded into the `TokenResolver`.

Also also, since you are using the provided config as is, please note that first, it is defined to listen on port 80, secondly it listens on `contest.clashing-coders.at`, so you won't be able to access it with `localhost`. You might want to edit your `/etc/hosts` file to resolve that URL back to localhost, or nginx won't be able to tell what you are trying to do.
